import React from "react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div className=" w-[85%] mx-auto py-8">
      <div className=" mx-auto   rounded-lg py-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-6">
          Privacy Policy
        </h1>
        <p className="text-gray-700 mb-4">
          Welcome to [Your Online Notary Website Name]! Your privacy is
          important to us. This Privacy Policy outlines how we collect, use, and
          protect your information when you visit or interact with our website.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6 mb-4">
          1. Information We Collect
        </h2>
        <p className="text-gray-700 mb-4">
          When you use our website, we may collect personal information such as
          your name, email address, phone number, and any documents you upload
          for notarization purposes.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6 mb-4">
          2. How We Use Your Information
        </h2>
        <ul className="list-disc list-inside text-gray-700 mb-4">
          <li>To provide you with our notary services.</li>
          <li>To communicate with you about your requests or orders.</li>
          <li>To improve the functionality of our website and services.</li>
          <li>
            To comply with legal obligations, such as recordkeeping for
            notarizations.
          </li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-800 mt-6 mb-4">
          3. Data Security
        </h2>
        <p className="text-gray-700 mb-4">
          We use industry-standard security measures to protect your personal
          data. However, no method of transmission over the internet is 100%
          secure, so we cannot guarantee absolute security.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6 mb-4">
          4. Sharing of Information
        </h2>
        <p className="text-gray-700 mb-4">
          We do not sell, trade, or rent your personal information to others.
          However, we may share your information with third-party service
          providers that assist us in delivering our services, as required by
          law.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6 mb-4">
          5. Your Rights
        </h2>
        <p className="text-gray-700 mb-4">
          You have the right to access, update, or delete your personal
          information. To exercise these rights, please contact us at{" "}
          <a
            href="mailto:support@yourwebsite.com"
            className="text-blue-600 underline"
          >
            support@yourwebsite.com
          </a>
          .
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6 mb-4">
          6. Changes to This Policy
        </h2>
        <p className="text-gray-700 mb-4">
          We reserve the right to update this Privacy Policy from time to time.
          Any changes will be posted on this page with a revised "Last Updated"
          date.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6 mb-4">
          7. Contact Us
        </h2>
        <p className="text-gray-700 mb-4">
          If you have any questions or concerns about this Privacy Policy,
          please contact us at{" "}
          <a
            href="mailto:support@yourwebsite.com"
            className="text-blue-600 underline"
          >
            support@yourwebsite.com
          </a>
          .
        </p>

        <p className="text-sm text-gray-500 mt-8">
          Last Updated: [Insert Date]
        </p>
      </div>
    </div>
  );
};

export default page;
