import Footer from "./Components/H&F/Footer";
import Navbar from "./Components/H&F/Navbar";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Script from "next/script";
export const metadata = {
  title: "Home - Online Notary layout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={``}>
        <Script
          id="tawk-to-script"
          src={process.env.NEXT_PUBLIC_TAWK_SRC}
          strategy="lazyOnload"
        />
        <Navbar />
        <ToastContainer /> {children} <Footer />
      </body>
    </html>
  );
}
