import Footer from "./Components/H&F/Footer";
import Navbar from "./Components/H&F/Navbar";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Script from "next/script";
import Head from "next/head";

export const metadata = {
  title: "Home - Online Notary Layout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Page Metadata */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />

        {/* Google Site Verification */}
        <meta
          name="google-site-verification"
          content="8LqiwoyptpRB7mysJrpA7v6FeW6kycJ2B8ZZd3M2J6w"
        />
      </Head>

      <body>
        {/* Google Analytics */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-3F0W62LXV1"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){ dataLayer.push(arguments); }
            gtag('js', new Date());
            gtag('config', 'G-3F0W62LXV1');
          `}
        </Script>

        {/* Tawk.to Live Chat */}
        {process.env.NEXT_PUBLIC_TAWK_SRC && (
          <Script
            id="tawk-to-script"
            src={process.env.NEXT_PUBLIC_TAWK_SRC}
            strategy="lazyOnload"
          />
        )}

        {/* Page Layout */}
        <Navbar />
        <ToastContainer />
        {children}
        <Footer />
      </body>
    </html>
  );
}
