import Footer from "./Components/H&F/Footer";
import Navbar from "./Components/H&F/Navbar";
import "./globals.css";
import { ToastContainer } from "react-toastify";
export const metadata = {
  title: "Home - Online Notary layout",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={``}>
        <Navbar />
        <ToastContainer /> {children} <Footer />
      </body>
    </html>
  );
}
