import React from "react";
import Hero from "../Components/LawfirmPage/Hero";
import Digitalization from "../Components/LawfirmPage/Digitalization";
import AdvantagesSection from "../Components/LawfirmPage/AdvantagesSection";
import HowItWorks from "../Components/LawfirmPage/HowItWorks";
import Faq from "../Components/LawfirmPage/Faq";
import FAQSection from "../Components/Home/FAQSection";
import AdvantagesForClients from "../Components/LawfirmPage/AdvantagesForClients";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <Hero />
      <Digitalization />
      <HowItWorks />
      <AdvantagesSection />
      <AdvantagesForClients />
      <FAQSection />
    </div>
  );
};

export default page;
