export const metadata = {
  title: "how it works",
  description: "Generated by create next app",
};

export default function BusinessLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>{children}</body>
    </html>
  );
}
