import React from "react";
import Login from "../Components/User Login/Login";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div>
      <Login />
    </div>
  );
};

export default page;
