export const metadata = {
  title: "Bank Service Page",
  description: "Generated by create next app",
};

export default function BankLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>{children}</body>
    </html>
  );
}
